# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGridLayout, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QSplitter,
    QStatusBar, QWidget)

from plotwidget import PlotWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.WindowModality.NonModal)
        MainWindow.resize(1161, 568)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.plotWidget = PlotWidget(self.centralwidget)
        self.plotWidget.setObjectName(u"plotWidget")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)

        self.gridLayout.addWidget(self.plotWidget, 1, 0, 1, 1)

        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy1)
        self.widget.setMinimumSize(QSize(0, 160))
        self.widget.setMaximumSize(QSize(16777215, 160))
        self.buttonSimulate = QPushButton(self.widget)
        self.buttonSimulate.setObjectName(u"buttonSimulate")
        self.buttonSimulate.setGeometry(QRect(10, 130, 75, 24))
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 40, 70, 16))
        self.label_7 = QLabel(self.widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(330, 10, 75, 16))
        self.splitter_4 = QSplitter(self.widget)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setGeometry(QRect(110, 100, 201, 22))
        self.splitter_4.setOrientation(Qt.Orientation.Horizontal)
        self.inputMaxJerk = QLineEdit(self.splitter_4)
        self.inputMaxJerk.setObjectName(u"inputMaxJerk")
        self.inputMaxJerk.setInputMask(u"")
        self.inputMaxJerk.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.inputMaxJerk.setClearButtonEnabled(True)
        self.splitter_4.addWidget(self.inputMaxJerk)
        self.label_6 = QLabel(self.splitter_4)
        self.label_6.setObjectName(u"label_6")
        self.splitter_4.addWidget(self.label_6)
        self.splitter_2 = QSplitter(self.widget)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setGeometry(QRect(109, 40, 195, 22))
        self.splitter_2.setOrientation(Qt.Orientation.Horizontal)
        self.inputMaxVelocity = QLineEdit(self.splitter_2)
        self.inputMaxVelocity.setObjectName(u"inputMaxVelocity")
        self.inputMaxVelocity.setInputMask(u"")
        self.inputMaxVelocity.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.inputMaxVelocity.setClearButtonEnabled(True)
        self.splitter_2.addWidget(self.inputMaxVelocity)
        self.label_3 = QLabel(self.splitter_2)
        self.label_3.setObjectName(u"label_3")
        self.splitter_2.addWidget(self.label_3)
        self.label_5 = QLabel(self.widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(11, 100, 48, 16))
        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 70, 93, 16))
        self.splitter = QSplitter(self.widget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(416, 9, 185, 22))
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.inputDisplacement = QLineEdit(self.splitter)
        self.inputDisplacement.setObjectName(u"inputDisplacement")
        self.inputDisplacement.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.inputDisplacement.setInputMask(u"")
        self.inputDisplacement.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.inputDisplacement.setClearButtonEnabled(True)
        self.splitter.addWidget(self.inputDisplacement)
        self.label_8 = QLabel(self.splitter)
        self.label_8.setObjectName(u"label_8")
        self.splitter.addWidget(self.label_8)
        self.splitter_3 = QSplitter(self.widget)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setGeometry(QRect(109, 70, 201, 22))
        self.splitter_3.setOrientation(Qt.Orientation.Horizontal)
        self.inputMaxAcceleration = QLineEdit(self.splitter_3)
        self.inputMaxAcceleration.setObjectName(u"inputMaxAcceleration")
        self.inputMaxAcceleration.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.inputMaxAcceleration.setClearButtonEnabled(True)
        self.splitter_3.addWidget(self.inputMaxAcceleration)
        self.label_4 = QLabel(self.splitter_3)
        self.label_4.setObjectName(u"label_4")
        self.splitter_3.addWidget(self.label_4)
        self.label_10 = QLabel(self.widget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 10, 75, 16))
        self.splitter_5 = QSplitter(self.widget)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setEnabled(True)
        self.splitter_5.setGeometry(QRect(109, 10, 195, 22))
        self.splitter_5.setOrientation(Qt.Orientation.Horizontal)
        self.inputInitialVelocity = QLineEdit(self.splitter_5)
        self.inputInitialVelocity.setObjectName(u"inputInitialVelocity")
        self.inputInitialVelocity.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.inputInitialVelocity.setInputMask(u"")
        self.inputInitialVelocity.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.inputInitialVelocity.setClearButtonEnabled(True)
        self.splitter_5.addWidget(self.inputInitialVelocity)
        self.label_9 = QLabel(self.splitter_5)
        self.label_9.setObjectName(u"label_9")
        self.splitter_5.addWidget(self.label_9)
        self.splitter_6 = QSplitter(self.widget)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setGeometry(QRect(630, 10, 171, 22))
        self.splitter_6.setOrientation(Qt.Orientation.Horizontal)
        self.label_11 = QLabel(self.splitter_6)
        self.label_11.setObjectName(u"label_11")
        self.splitter_6.addWidget(self.label_11)
        self.comboPlot1 = QComboBox(self.splitter_6)
        self.comboPlot1.addItem("")
        self.comboPlot1.addItem("")
        self.comboPlot1.addItem("")
        self.comboPlot1.addItem("")
        self.comboPlot1.setObjectName(u"comboPlot1")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.comboPlot1.sizePolicy().hasHeightForWidth())
        self.comboPlot1.setSizePolicy(sizePolicy2)
        self.comboPlot1.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.splitter_6.addWidget(self.comboPlot1)
        self.splitter_7 = QSplitter(self.widget)
        self.splitter_7.setObjectName(u"splitter_7")
        self.splitter_7.setGeometry(QRect(630, 40, 171, 22))
        self.splitter_7.setOrientation(Qt.Orientation.Horizontal)
        self.label_12 = QLabel(self.splitter_7)
        self.label_12.setObjectName(u"label_12")
        self.splitter_7.addWidget(self.label_12)
        self.comboPlot2 = QComboBox(self.splitter_7)
        self.comboPlot2.addItem("")
        self.comboPlot2.addItem("")
        self.comboPlot2.addItem("")
        self.comboPlot2.addItem("")
        self.comboPlot2.setObjectName(u"comboPlot2")
        sizePolicy2.setHeightForWidth(self.comboPlot2.sizePolicy().hasHeightForWidth())
        self.comboPlot2.setSizePolicy(sizePolicy2)
        self.comboPlot2.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.splitter_7.addWidget(self.comboPlot2)
        self.cbTimeConstraint = QCheckBox(self.widget)
        self.cbTimeConstraint.setObjectName(u"cbTimeConstraint")
        self.cbTimeConstraint.setGeometry(QRect(330, 40, 71, 20))
        self.splitter_8 = QSplitter(self.widget)
        self.splitter_8.setObjectName(u"splitter_8")
        self.splitter_8.setGeometry(QRect(416, 40, 164, 22))
        self.splitter_8.setOrientation(Qt.Orientation.Horizontal)
        self.inputTimeConstraint = QLineEdit(self.splitter_8)
        self.inputTimeConstraint.setObjectName(u"inputTimeConstraint")
        self.inputTimeConstraint.setEnabled(False)
        self.inputTimeConstraint.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.inputTimeConstraint.setInputMask(u"")
        self.inputTimeConstraint.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.inputTimeConstraint.setClearButtonEnabled(True)
        self.splitter_8.addWidget(self.inputTimeConstraint)
        self.label_13 = QLabel(self.splitter_8)
        self.label_13.setObjectName(u"label_13")
        self.splitter_8.addWidget(self.label_13)
        self.line = QFrame(self.widget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(805, 0, 20, 160))
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy3)
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_14 = QLabel(self.widget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(830, 10, 101, 16))
        self.label_result_total_time = QLabel(self.widget)
        self.label_result_total_time.setObjectName(u"label_result_total_time")
        self.label_result_total_time.setGeometry(QRect(930, 10, 200, 16))
        sizePolicy2.setHeightForWidth(self.label_result_total_time.sizePolicy().hasHeightForWidth())
        self.label_result_total_time.setSizePolicy(sizePolicy2)
        self.label_result_max_velocity = QLabel(self.widget)
        self.label_result_max_velocity.setObjectName(u"label_result_max_velocity")
        self.label_result_max_velocity.setGeometry(QRect(930, 30, 200, 16))
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.label_result_max_velocity.sizePolicy().hasHeightForWidth())
        self.label_result_max_velocity.setSizePolicy(sizePolicy4)
        self.label_15 = QLabel(self.widget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(830, 30, 101, 16))
        self.label_16 = QLabel(self.widget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(830, 50, 101, 16))
        self.label_result_max_acceleration = QLabel(self.widget)
        self.label_result_max_acceleration.setObjectName(u"label_result_max_acceleration")
        self.label_result_max_acceleration.setGeometry(QRect(930, 50, 200, 16))
        sizePolicy4.setHeightForWidth(self.label_result_max_acceleration.sizePolicy().hasHeightForWidth())
        self.label_result_max_acceleration.setSizePolicy(sizePolicy4)
        self.label_17 = QLabel(self.widget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(830, 70, 101, 16))
        self.label_result_motion_profile = QLabel(self.widget)
        self.label_result_motion_profile.setObjectName(u"label_result_motion_profile")
        self.label_result_motion_profile.setGeometry(QRect(930, 70, 200, 16))
        sizePolicy4.setHeightForWidth(self.label_result_motion_profile.sizePolicy().hasHeightForWidth())
        self.label_result_motion_profile.setSizePolicy(sizePolicy4)
        self.line_2 = QFrame(self.widget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(605, 0, 20, 160))
        sizePolicy3.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy3)
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.cbPlotSamplingPoints = QCheckBox(self.widget)
        self.cbPlotSamplingPoints.setObjectName(u"cbPlotSamplingPoints")
        self.cbPlotSamplingPoints.setGeometry(QRect(630, 70, 141, 20))

        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1161, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.buttonSimulate.setDefault(True)
        self.comboPlot1.setCurrentIndex(2)
        self.comboPlot2.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Third order motion simulator", None))
        self.buttonSimulate.setText(QCoreApplication.translate("MainWindow", u"Simulate", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Max velocity:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Displacement:", None))
        self.inputMaxJerk.setText(QCoreApplication.translate("MainWindow", u"10000", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"units/s3", None))
        self.inputMaxVelocity.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"units/s", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Max jerk:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Max acceleration:", None))
        self.inputDisplacement.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"units", None))
        self.inputMaxAcceleration.setInputMask("")
        self.inputMaxAcceleration.setText(QCoreApplication.translate("MainWindow", u"500", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"units/s2", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Initial velocity:", None))
        self.inputInitialVelocity.setText(QCoreApplication.translate("MainWindow", u"8.33", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"units/s", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Plot 1:", None))
        self.comboPlot1.setItemText(0, QCoreApplication.translate("MainWindow", u"None", None))
        self.comboPlot1.setItemText(1, QCoreApplication.translate("MainWindow", u"Displacement", None))
        self.comboPlot1.setItemText(2, QCoreApplication.translate("MainWindow", u"Velocity", None))
        self.comboPlot1.setItemText(3, QCoreApplication.translate("MainWindow", u"Acceleration", None))

        self.comboPlot1.setCurrentText(QCoreApplication.translate("MainWindow", u"Velocity", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Plot 2:", None))
        self.comboPlot2.setItemText(0, QCoreApplication.translate("MainWindow", u"None", None))
        self.comboPlot2.setItemText(1, QCoreApplication.translate("MainWindow", u"Displacement", None))
        self.comboPlot2.setItemText(2, QCoreApplication.translate("MainWindow", u"Velocity", None))
        self.comboPlot2.setItemText(3, QCoreApplication.translate("MainWindow", u"Acceleration", None))

        self.comboPlot2.setCurrentText(QCoreApplication.translate("MainWindow", u"Displacement", None))
        self.cbTimeConstraint.setText(QCoreApplication.translate("MainWindow", u"Time:", None))
        self.inputTimeConstraint.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"s", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Total time:", None))
        self.label_result_total_time.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.label_result_max_velocity.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Max velocity:", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Max acceleration:", None))
        self.label_result_max_acceleration.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Motion profile:", None))
        self.label_result_motion_profile.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.cbPlotSamplingPoints.setText(QCoreApplication.translate("MainWindow", u"Plot sampling points", None))
    # retranslateUi

